In [7]:
#monte-carlo to price the option
import numpy as np
s0,vol,tao,q,r=100,0.30,1,0,0


In [8]:
#discount factor
disc=np.exp(-r*tao)

mu,sigma=(r-q-0.5*vol*vol)*tao,vol*np.sqrt(tao)

In [9]:
N=1000000
n=int(N/10)
s=s0*np.random.lognormal(mu,sigma,N)
#lognormal([mean, sigma, size])
s[::n]

array([114.52936617,  88.81371544, 100.14521491,  87.41005208,
       160.21874559,  75.19538393,  95.12339869, 121.13935226,
        59.37368511, 104.47208007])

In [91]:
K=100
call= lambda S: (S-K) if S>K else 0
put=lambda S:(K-S) if S<K else 0

In [92]:
v_call = np.vectorize(call)
v_put=np.vectorize(put)

In [93]:
call_T = v_call(s)
call_T[::n]


array([ 0,  0, 37,  0, 50,  5,  0, 11,  0,  0])

In [94]:
put_T=v_put(s)
put_T[::n]

array([28.13725394,  2.50709064,  0.        , 23.5554642 ,  0.        ,
        0.        , 29.49086791,  0.        , 48.93837437, 22.59705744])

In [95]:
call_0=call_T.mean()*disc
put_0=put_T.mean()*disc

In [96]:
put_0

11.93259298488614

In [97]:
#Greeks--Delta
np.random.seed(0)

In [98]:
np.random.seed(1)

s1 = s0*np.random.lognormal(mu,sigma,N)

In [99]:
temp=s0+0.01




In [100]:
np.random.seed(1)
s2=temp*np.random.lognormal(mu,sigma,N)

In [101]:
call1=disc*v_call(s1).mean()
call2=disc*v_call(s2).mean()
print(call1,call2)

11.92950264115745 11.935104380156503


In [102]:
delta=(call2-call1)/0.01
delta

0.5601738999052586

In [103]:
#Greek-gamma
temp1=s0+0.02


In [104]:
np.random.seed(1)
s5=temp1*np.random.lognormal(mu,sigma,N)

In [105]:
call1=disc*v_call(s2).mean()
call5=disc*v_call(s5).mean()
#print(call1,call5)

In [106]:
delta1=(call5-call1)/0.01

gamma=(delta1-delta)/0.01
gamma

0.013806132983518182

In [107]:
#Greek-Vega
vol1 = vol+0.01
sigma1 = vol1*np.sqrt(tao)
mu1 = r - q -0.5*vol1*vol1*tao

In [108]:
np.random.seed(1)
s3=s0*np.random.lognormal(mu1,sigma1,N)

In [130]:
call1=disc*v_call(s1).mean()
call3=disc*v_call(s3).mean()
print(call1,call3)

11.92950264115745 12.323881112942411


In [110]:
vega=(call3-call1)/0.01
vega

39.4378471784961

In [174]:
#Greek-Rho
r1=r+0.01
mu2=(r1-q-0.5*vol*vol)*tao
sigma=vol*np.sqrt(tao)
disc_new=np.exp(-r1*tao)

In [175]:
np.random.seed(1)
s4=s0*np.random.lognormal(mu2,sigma,N)

In [179]:
call1=disc*v_call(s1).mean()
call4=disc_new*v_call(s4).mean()
print(call1,call4)

11.92950264115745 12.374553552853572


In [180]:
Rho=(call4-call1)/0.01
Rho

44.50509116961214

In [169]:
#Greeks-Theta
t1=tao+0.01
sigma2 = vol*np.sqrt(t1)
mu3 = r - q -0.5*vol*vol*t1


In [116]:
np.random.seed(1)
s6=s0*np.random.lognormal(mu3,sigma2,N)

In [117]:
call1=disc*v_call(s1).mean()
call6=disc*v_call(s6).mean()
print(call1,call6)

11.92950264115745 11.988531419793379


In [118]:
theta=(call6-call1)/0.01
theta

5.90287786359287

In [183]:
with open('result.txt','a') as out:
    out.writelines('The result of options_mc is:\n')
    out.writelines('Delta: '+str(delta)+'\n')
    out.writelines('Gamma: '+str(gamma)+'\n')
    out.writelines('Rho: '+str(Rho)+'\n')
    out.writelines('Theta: '+str(theta)+'\n')
    out.writelines('Vega: '+str(vega)+'\n')

In [5]:
 a=[1,2,3]
a.mean()

AttributeError: 'list' object has no attribute 'mean'

In [10]:
type(s)

numpy.ndarray